python ~/bin/tools/tetra/lr.py --Y 'form' --X 'chg' 'mag' 'volume' 'l_bond' 'n_bond' 'grosspop' 'madelung' '-ICOHPm' '-ICOHPn' 'ICOBIm' 'ICOBIn' '-ICOOPm' '-ICOOPn' 'pauling' 'ion1' 'ion2' 'ion12' 'ion3' 'Natom' 'mass' 'density' 'Vatom' 'dipole' 'Rcoval' 'Rmetal' 'Rvdw' 'Tboil' 'Tmelt' 'Hevap' 'Hfus' 'Hform' --row '3d' '4d' '5d' --output 'form'

python ~/bin/tools/tetra/lr.py --Y 'form' --X 'chg' 'mag' 'volume' 'l_bond' 'n_bond' 'grosspop' 'madelung' '-ICOHPm' '-ICOHPn' 'ICOBIm' 'ICOBIn' '-ICOOPm' '-ICOOPn' 'pauling' 'ion1' 'ion2' 'ion12' 'ion3' 'Natom' 'mass' 'density' 'Vatom' 'dipole' 'Rcoval' 'Rmetal' 'Rvdw' 'Tboil' 'Tmelt' 'Hevap' 'Hfus' 'Hform' --row '3d' --output 'form3d'

python ~/bin/tools/tetra/lr.py --Y 'form' --X 'chg' 'mag' 'volume' 'l_bond' 'n_bond' 'grosspop' 'madelung' '-ICOHPm' '-ICOHPn' 'ICOBIm' 'ICOBIn' '-ICOOPm' '-ICOOPn' 'pauling' 'ion1' 'ion2' 'ion12' 'ion3' 'Natom' 'mass' 'density' 'Vatom' 'dipole' 'Rcoval' 'Rmetal' 'Rvdw' 'Tboil' 'Tmelt' 'Hevap' 'Hfus' 'Hform' --row '4d' --output 'form4d'

python ~/bin/tools/tetra/lr.py --Y 'form' --X 'chg' 'mag' 'volume' 'l_bond' 'n_bond' 'grosspop' 'madelung' '-ICOHPm' '-ICOHPn' 'ICOBIm' 'ICOBIn' '-ICOOPm' '-ICOOPn' 'pauling' 'ion1' 'ion2' 'ion12' 'ion3' 'Natom' 'mass' 'density' 'Vatom' 'dipole' 'Rcoval' 'Rmetal' 'Rvdw' 'Tboil' 'Tmelt' 'Hevap' 'Hfus' 'Hform' --row '5d' --output 'form5d'

python ~/bin/tools/tetra/lr.py --Y 'form' --X 'chg' 'mag' 'volume' 'l_bond' 'n_bond' 'grosspop' 'madelung' '-ICOHPm' '-ICOHPn' 'ICOBIm' 'ICOBIn' '-ICOOPm' '-ICOOPn' 'pauling' 'ion1' 'ion2' 'ion12' 'ion3' 'Natom' 'mass' 'density' 'Vatom' 'dipole' 'Rcoval' 'Rmetal' 'Rvdw' 'Tboil' 'Tmelt' 'Hevap' 'Hfus' 'Hform' --row '4d' --output 'form4d'

python ~/bin/tools/tetra/lr.py --Y 'form' --X 'chg' 'mag' 'volume' 'l_bond' 'n_bond' 'grosspop' 'madelung' '-ICOHPm' '-ICOHPn' 'ICOBIm' 'ICOBIn' '-ICOOPm' '-ICOOPn' 'pauling' 'ion1' 'ion2' 'ion12' 'ion3' 'Natom' 'mass' 'density' 'Vatom' 'dipole' 'Rcoval' 'Rmetal' 'Rvdw' 'Tboil' 'Tmelt' 'Hevap' 'Hfus' 'Hform' --row '4d5d' --output 'form4d5d'